version: '3'

networks:
  lan:

services:

  core1:
    image: neo4j
    networks:
      - lan
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - $PWD/neo4j/neo4j-core1/data:/data
      - $PWD/neo4j/neo4j-core1/conf:/conf
      - $PWD/neo4j/neo4j-core1/plugins:/plugins
    environment:
      - NEO4J_AUTH=none
      - NEO4J_dbms_memory_heap_maxSize=15G
        #      - NEO4J_AUTH=neo4j/changeme
